softwarecrafters/website

communities/alicante.json
communities/murcia.json

Add Alicante and Murcia communities in Spain

Add Alicante and Murcia communities

---

communities/ruhrgebiet.json

Events of this community take place in the cities Dortmund and Bochum by now. Therefore I chose coordinates somewhere between those two. ;-)

Adding Softwerkskammer Ruhrgebiet (Germany)

---

communities/turkey.json

we are proud to be a part of this community.

adds software crafters turkey to community.

---

communities/frenchriviera.json

Adding French Riviera Software Craftsmanship Community.
Cc @cceelen @randspy

Add French Riviera Meetup

---

communities/southtyrol.json

I hope the order of lat/lng is correct as this often depends on the underlying map that is being used :smiley:

add Software Craftsmanship South Tyrol

---

communities/antwerpen.json
communities/gent.json
communities/hasselt.json

Due to Belgium's geography, there is a single Socrates community which organises meetups in different cities. I've tried to reflect this by making three items.

SocratesBe has multiple cities

---

communities/glasgow.json

CodeCraft is a meetup for software crafters in Glasgow, Scotland.

Add CodeCraft for Glasgow

---

communities/rostock.json

Add Rostock community

---

communities/riga.json
conferences/devternity.json

add major events in Riga - LatCraft and DevTernity

add major events in Riga - LatCraft and DevTernity

---

communities/dublin.json

I would like to add Dublin Software Crafters community to the list.

Add Dublin Software Crafters community

---

communities/dijon.json

I think I have done things cleaner this time, sorry for the merge conflict

Trying again

---

communities/lyon.json

Hi there ! Someone finally had the motivation to put our community on the map. Thanks for the work :smiley_cat:

add the community of Lyon

---

conferences/socrates-can.json

Same dates as in the website http://socracan.com/

Update dates for SoCraTes Canaries 2019

---

communities/pune.json

Hello Dear fellow craftspeople,
We have recently started a community in Pune, India region with a mission to spread awareness about "software as a craft" and technical excellence. 
We are growing in strength slowly and steadily wish us luck :)
Thanks,

Adding Pune software craftspeople community

---

communities/casablanca.json

Hi,
Would you kindly review and accept this update with the local Moroccan crafters' community coordinates ?
Best Regards,
Sallah Kokaina

Casablanca, Morocco local software crafters community

---

communities/manila.json

Adding in Software Crafters Manila [softwarecrafters.ph](https://softwarecrafters.ph).

Software Crafters Manila

---

conferences/jscraftcamp.json

See https://softwarecrafters.slack.com/archives/C2M4QC7NC/p1582744206002200

2020 dates for JSCraftCamp

---

communities/girona.json

Added new SW Crafters community created in Girona.

Add Software Crafters Girona

---

communities/vienna-mob-programming-meetup.json

I would like to add the Austrian Mob-Programming Meetup to the website.

Add Austrian (Vienna) Mob-Programming Meetup

---

conferences/scunconf.json

fix(scunconf): change name, new date, add code of conduct

---

README.md

I propose to use `main` as the name for the main branch, instead of `master`.
If accepted this I will push a new branch based off `master` as `main` and make it the default branch, afterwards I will delete `master`.

Use main instead of master for the main branch

---

conferences/socrates-family-ch.json

Adding SoCraTes Family Switzerland to the agenda

---

communities/zurich.json
conferences/socrates-ch.json
conferences/socrates-day-ch.json

Last fix for tonight. Sorry about that.

Improving Geo Cordinates, and assigning icon to the right event

---

conferences/agilecrete.json

Back to in-person events 🎉 🎉 🎉

Adds AgileCrete / SoCraTes Crete 2022

---

communities/acoruna.json

i am starting the software crafter community here in coruña

Create acoruna software crafters community

---

communities/cordoba.json

Hey! I would add the Córdoba Software Crafters community to the map 😊

Add Córdoba (Spain) Software Crafters community

---

conferences/socrates-ca.json

Hello there 👋 
We are organizing a 2nd edition of SoCraTes Canada! It will happen in October (13-15), so people can enjoy the beautiful colors of Canada while joining us 🍁 
We also have updated our Code of Conduct to be more exhaustive.
Thanks!

Update SoCraTes Canada dates (2nd edition)

---

conferences/socrates-de.json

According to https://www.socrates-conference.de/

Update date of next SoCraTes Germany

---

communities/karachi.json

We have moved our website from github to notion

Updated website link for Karachi.json

---

conferences/jalba-unconf.json

Add JAlba Unconference (suggested by patrick Baumgartner at Voxxed Days CERN)

Add JAlba Unconference

---

communities/quebec.json

There's a new community that was created in Québec City a few months ago: https://www.meetup.com/fr-FR/software-crafters-quebec/

Add Québec community

---

conferences/socrates-uk.json

We have a date and a new location for the UK edition :)

Update SoCraTes UK 2024

---

communities/lille.json

Lille's meetup has been renamed

---

conferences/socrates-uk.json

Co-authored-by: Alexander Alemayhu <alexander@alemayhu.com>

Update SoCraTes UK 2025

---

communities/saopaulo.json

this pr is to update the meetup link, the previous one seems to not work anymore

update são paulo crafters meetup link
